// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDYvOA2v-942qs-cNzIZKdjRBuTA7BhKM',
    appId: '1:711111316076:web:207c5545109c7894fa3e49',
    messagingSenderId: '711111316076',
    projectId: 'fluttertask-6ca3e',
    authDomain: 'fluttertask-6ca3e.firebaseapp.com',
    storageBucket: 'fluttertask-6ca3e.firebasestorage.app',
    measurementId: 'G-RMW3ES1J6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpLOiMC0KAHzQfYwT9l38oXVVGvMbWR9M',
    appId: '1:711111316076:android:ea59d34011006218fa3e49',
    messagingSenderId: '711111316076',
    projectId: 'fluttertask-6ca3e',
    storageBucket: 'fluttertask-6ca3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKC96LDxZzlWNvFhAthkqOgJYhU3cIbPI',
    appId: '1:711111316076:ios:98ea39128c4a2b65fa3e49',
    messagingSenderId: '711111316076',
    projectId: 'fluttertask-6ca3e',
    storageBucket: 'fluttertask-6ca3e.firebasestorage.app',
    iosBundleId: 'com.example.gamevibe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKC96LDxZzlWNvFhAthkqOgJYhU3cIbPI',
    appId: '1:711111316076:ios:98ea39128c4a2b65fa3e49',
    messagingSenderId: '711111316076',
    projectId: 'fluttertask-6ca3e',
    storageBucket: 'fluttertask-6ca3e.firebasestorage.app',
    iosBundleId: 'com.example.gamevibe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDYvOA2v-942qs-cNzIZKdjRBuTA7BhKM',
    appId: '1:711111316076:web:b0586fbffc7e7f68fa3e49',
    messagingSenderId: '711111316076',
    projectId: 'fluttertask-6ca3e',
    authDomain: 'fluttertask-6ca3e.firebaseapp.com',
    storageBucket: 'fluttertask-6ca3e.firebasestorage.app',
    measurementId: 'G-Y69ST8RJRL',
  );

}